- name: Create VM from image
  hosts: localhost
  gather_facts: true
  become: true
  vars:
    pool_dir: "/var/lib/libvirt/images"
    vm: vm
    vcpus: 1
    ram_mb: 1024

  tasks:
    - name: Provision VM
      include_role:
        name: provision
      vars:
        libvirt_pool_dir: "{{ pool_dir }}"
        vm_name: "{{ vm }}"
        vm_vcpus: "{{ vcpus }}"
        vm_ram_mb: "{{ ram_mb }}"